language: python

python:
  - "3.5"

sudo: required

# if specific versions of docker or docker-compose are needed, see travis-CI docs
services:
  - docker 

before_install:
  - docker pull mysql:5.7.14
  - mkdir db
  - >
    docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS'
    -v `pwd`/db:/var/lib/mysql mysql:5.7.14
  - sleep 20
  - >
    docker run -it --name mysql-cmd --rm --link mysql:db mysql:5.7.14
    mysql -uroot -p'$3cureUS' -h db -v -e
    "CREATE DATABASE cs4501 CHARACTER SET utf8;
    CREATE USER 'www'@'%' IDENTIFIED BY '\$3cureUS';
    GRANT ALL PRIVILEGES ON *.* TO 'www'@'%';
    grant all on cs4501.* to 'www'@'%';
    grant all on test_cs4501.* to 'www'@'%';"

install:
- pip install -r requirements-travis.txt

before_script: 
 - docker-compose up -d

script:
 - sleep 20
 - docker exec -it models bash -c "python manage.py test"
 - docker exec -it selenium-test bash -c "python tests.py"