# Generated by Django 2.2.4 on 2020-05-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recommendation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
