# Generated by Django 2.2.4 on 2020-03-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='numberBought',
            field=models.IntegerField(default=0),
        ),
    ]
