# Generated by Django 2.2.4 on 2020-05-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_item_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='recommendation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
