# Generated by Django 2.2.4 on 2020-02-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_item_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
